import os
import logging
import pandas as pd
import yfinance as yf

# Configure pipeline audit logging
os.makedirs("logs", exist_ok=True)
logging.basicConfig(
    filename="logs/pipeline_audit.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a"
)

# Asset ticker configuration
TICKERS = {
    "GOLD": "GC=F",
    "SILVER": "SI=F",
    "SP500": "^GSPC",
    "dxy": "DX-Y.NYB",
    "VIX": "^VIX"
}

def fetch_asset_data(ticker_symbol: str, start_date: str = "2018-01-01") -> pd.DataFrame:
    """Downloads daily OHLCV market data via yfinance."""
    logging.info(f"Downloading {ticker_symbol} market data from {start_date}...")
    df = yf.download(ticker_symbol, start=start_date, progress=False)
    
    if df.empty:
        logging.error(f"Failed to retrieve data for ticker: {ticker_symbol}")
        raise ValueError(f"No data returned for {ticker_symbol}")
    
    # Flatten MultiIndex columns if generated by yfinance
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
        
    df = df[['Open', 'High', 'Low', 'Close', 'Volume']].dropna(how='all')
    df.index = pd.to_datetime(df.index).tz_localize(None)
    return df

def synchronize_calendars(data_dict: dict) -> pd.DataFrame:
    """
    Aligns non-synchronous asset schedules (e.g., US equity holidays vs global commodity trading hours).
    Consolidates Close prices and forward-fills calendar gaps up to 3 consecutive days.
    """
    logging.info("Aligning multi-asset trading calendars...")
    
    close_prices = {name: df['Close'] for name, df in data_dict.items()}
    combined = pd.DataFrame(close_prices)
    
    # Chronological sort and forward fill short gap windows
    combined = combined.sort_index().ffill(limit=3)
    
    # Drop initial dates prior to complete asset overlap
    combined = combined.dropna()
    
    logging.info(f"Calendar synchronization complete. Dataset dimensions: {combined.shape}")
    return combined

def main():
    try:
        raw_data = {}
        for asset_name, ticker in TICKERS.items():
            df = fetch_asset_data(ticker)
            raw_data[asset_name] = df
            
        aligned_df = synchronize_calendars(raw_data)
        
        output_path = "data/raw/synchronized_close_prices.parquet"
        aligned_df.to_parquet(output_path)
        logging.info(f"Saved raw synchronized dataset to {output_path}")
        print(f"Data ingestion complete. Aligned {len(aligned_df)} trading days across {len(TICKERS)} assets.")

    except Exception as e:
        logging.error(f"Pipeline execution halted in fetch_data: {str(e)}")
        print(f"Ingestion Error: {str(e)}")

if __name__ == "__main__":
    main()